server:
  port: 7080
  servlet:
    context-path: /erap-service

spring:
  application:
    name: erap-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bdl_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Meruert19}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # update | create | validate | none
    show-sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: ${FEIGN_CLIENT_CONNECT_TIMEOUT:30000}
            readTimeout: ${FEIGN_CLIENT_READ_TIMEOUT:90000}
            loggerLevel: ${FEIGN_CLIENT_LOGLEVEL:full}

certificate:
  refresh:
    interval: ${CERTIFICATE_REFRESH_INTERVAL:10800000} # 3 hours in milliseconds

logging:
  file:
    name: /app/logs/erap-service.log
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    jdk:
      internal:
        httpclient: DEBUG
    kz:
      altyn:
        i:
          contactservice:
            external:
              client: DEBUG
  pattern:
    console: ${LOGGING_FORMAT:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} [%X{rid:-00000000000000000000000000000000}] %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx}
    file: ${LOGGING_FORMAT:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} [%X{rid:-00000000000000000000000000000000}] %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx}
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10

services:
  smartbridge:
    name: ${SERVICE_SMARTBRIDGE_NAME:smart-bridge-service}
    host: ${SERVICE_SMARTBRIDGE_HOST:http://localhost:8081/vshep/v1}
  smartbridge-test:
    name: ${SERVICE_SMARTBRIDGE_NAME_TEST:smart-bridge-service-test}
    host: ${SERVICE_SMARTBRIDGE_HOST_TEST:http://localhost:8082/vshep/v1}

signature:
  current-verify-alg: current.verify.alg # Gost2015_512
  current-sign-alg: current.sign.alg # Gost2015_512
  secret-storage:
    secret-path: ${SECRET_STORAGE_PATH:secretstorage/secrets-and-configs.json}
  paths:
    my-p12: my.p12.in.base64
    my-p12-pwd: my.p12.password